name: Build RPM and Store

on:
  push:
    branches:
      - package-build-in-github

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build RPM inside Docker
      run: |
        docker build --tag postprocess --target=package -f Dockerfile .
        docker run -v `pwd`:/store postprocess mv /root/rpmbuild/RPMS/noarch/postprocessing-2.6-1.noarch.rpm /store
        ls -la
      continue-on-error: false

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          postprocessing-2.6-1.noarch.rpm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


